#' -----------------------------------------
#' Create internals for functions necessary
#' to run exported functions in `SomaDataIO`
#' -----------------------------------------
library(here)
local({
  f <- c(
    "addAttributes",
    "addClass",
    "catchRunawayTabs",
    "cleanNames",
    "convertColMeta",
    "genRowNames",
    "getAdatVersion",
    "parseCheck",
    "syncColMeta"
  )
  withr::local_output_sink(here("R", "internals.R"))
  cat("# Internal functions to SomaDataIO\n")
  cat("# Generated by data-raw/create_internals.R\n")
  cat("# Do not edit by hand ...\n\n")
  for (i in f) {
    func <- getFromNamespace(i, ns = "SomaReadr")
    environment(func) <- .GlobalEnv
    cat(paste0(i, " <- "))
    print(func)
    cat("\n")
  }
})
