on:
  push:
    branches: [main, master]
    paths:
      - 'man/**'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'NEWS.md'
      - 'README.md'

name: Deploy pkgdown -> gh-pages

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            local::.
          needs: website

#      - name: Install Biobase
#        run: |
#          remotes::install_cran("BiocManager")
#          BiocManager::install("Biobase", version = "3.15")
#        shell: Rscript {0}

      - name: Install package
        run: |
          R CMD INSTALL --use-vanilla .

      - name: Deploy to GitHub pages 🚀
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
