# This is a basic workflow to sync the public repository -> SomaDataIO-internal
# This GHA is seldom used but it should be run occasionally
# to ensure the internal repo is up to date with the public side
# This GHA must be manually triggered from the GUI inside
#   git@github.com:SomaLogic/SomaDataIO-internal.git repository
# Author: Stu Field

on: workflow_dispatch

name: Public -> Internal

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: repo-sync
      env:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_SOMADATAIO_KEY }}
      run: |
        date > generated.txt
        mkdir ~/.ssh
        echo "$ssh_private_key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git \
          -c user.name="$GITHUB_ACTOR" \
          -c user.email="$GITHUB_ACTOR"@users.noreply.github.com \
          pull git@github.com:SomaLogic/SomaDataIO.git main
        git push origin main
