# This is a basic workflow to sync the public repository to SomaDataIO-internal
# With new workflows, this GHA is seldom used
# We do not sync between internal-public repos often
# It is now only manually triggered

on: workflow_dispatch

name: Public -> Internal

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: repo-sync
      env:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_SOMADATAIO_KEY }}
      run: |
        date > generated.txt
        mkdir ~/.ssh
        echo "$ssh_private_key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git -c user.name="$GITHUB_ACTOR" -c user.email="$GITHUB_ACTOR"@users.noreply.github.com push \
          git@github.com:SomaLogic/SomaDataIO-internal.git "$GITHUB_REF":main
